// let tokens = [];
const tokens = [
  ["color", "color", "color()"],
  ["true", "true/false", "true, false"],
  ["false", "true/false", "true, false"],
  ["on", "liga", "on()"],
  ["off", "desliga", "off()"],
  ["lumin", "luminosidade", "lumin()"],
  ["timer", "timer", "timer()"],
  ["getTime()", "getTime", "getTime()"],
  ["ifsuldeminas", "ifsuldeminas", "ifsuldeminas"],
  ["ife", "ife", "ife()"],
  ["elsee", "elsee", "elsee()"],
  [">=", "operadorRelacional", "<, >, >=, <="],
  ["<=", "operadorRelacional", "<, >, >=, <="],
  [">", "operadorRelacional", "<, >, >=, <="],
  ["<", "operadorRelacional", "<, >, >=, <="],
  [";", "endln", ";"],
  ["for", "for", "for"],
  ["(", "ParenteseAbre", "("],
  [")", "ParenteseFecha", ")"],
  ["{", "ChavesAbre", "{"],
  ["}", "ChavesFecha", "}"],
  ["[", "colcheteAbre", "["],
  ["]", "colcheteFecha", "]"],
  ["null", "null", "null"],
  ["!", "negacao", "!"],
  ["++", "incremento", "++"],
  ["==", "operadorRelacionalIgualDiferente", "==,!="],
  ["!=", "operadorRelacionalIgualDiferente", "==,!="],
  ["--", "decremento", "--"],
  ["boolean", "tipo", "boolean, enum, char, string,date"],
  ["enum", "tipo", "boolean, enum, char, string,date"],
  ["char", "tipo", "boolean, enum, char, string,date"],
  ["string", "tipo", "boolean, enum, char, string,date"],
  ["date", "tipo", "boolean, enum, char, string,date"],
  ["int", "tipoNumerico", "int, float, double"],
  ["float", "tipoNumerico", "int, float, double"],
  ["double", "tipoNumerico", "int, float, double"],
  ["=", "atribuicao", "="],
];
